server:
  port: ${SERVER_PORT:8080}


security:
  jwt:
    secret: ${JWT_SECRET:VerySecretKeyThatShouldBeLongEnoughChangeMe}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4200"
                  - "http://127.0.0.1:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - "Authorization"
                allowCredentials: true
                maxAge: 3600
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
            - RemoveRequestHeader=X-Forwarded-Host
          routes:
          - id: user
            uri: http://user-service:8080
            predicates:
              - Path=/api/v1/user/**

          - id: tmdb
            uri: http://tmdb-service:8080
            predicates:
              - Path=/api/v1/tmdb/**



logging:
  level:
    com.nextepisode: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG