package com.nextepisode.user_service.events;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;


@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserRegisteredEvent {
    /**
     * Unique event ID for tracking
     * ✅ CORRECTED: "eventId" (was "event_id")
     */
    @JsonProperty("eventId")
    private String eventId;

    /**
     * User ID generated by Auth Service
     * ✅ CORRECTED: "userId" (was "user_id")
     */
    @JsonProperty("userId")
    private Long userId;

    /**
     * Username
     */
    @JsonProperty("username")
    private String username;

    /**
     * User email
     */
    @JsonProperty("email")
    private String email;

    /**
     * When event was created
     * ✅ CORRECTED: "createdAt" (was "created_at")
     */
    @JsonProperty("createdAt")
    private LocalDateTime createdAt;

    /**
     * Event source service
     * ✅ CORRECTED: "sourceService" (was "source_service")
     */
    @JsonProperty("sourceService")
    private String sourceService;

    /**
     * Event version for backward compatibility
     */
    @JsonProperty("version")
    private String version = "1.0";
}